import{i,a as g,S as b}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();function w(){i.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"Oh, shit! Type something",messageColor:"white"})}async function y(e,t=1){const s="https://pixabay.com/api/",n=new URLSearchParams({key:"44041025-2e091a4b621ea033778029d2c",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{const{data:o}=await g(`${s}?${n}`);if(o.hits.length===0)i.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"&#11198; Sorry, there are no images matching your search query. Please, try again!",messageColor:"white"});else return o.hits}catch(o){console.error(o.message)}}let a;const u=document.querySelector(".gallery"),l=document.querySelector(".js-load-more");function L(e){u.innerHTML=e.map(t=>p(t)).join(""),a?a.refresh():a=new b(".gallery a",{captionDelay:250,captionsData:"alt"}),l.style.display="block"}l.addEventListener("click",v);let d=1;async function v(){d+=1,m();try{const e=await y(d);if(!e){f(),i.error({icon:"",backgroundColor:"blue",position:"topRight",message:"&#11198; We're sorry, but you've reached the end of search results.",messageColor:"white"}),l.style.display="none";return}u.insertAdjacentHTML("beforeend",e.map(n=>p(n)).join("")),a&&a.refresh();const s=u.lastElementChild.getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"}),d>=totalHits&&(l.style.display="none",i.error({icon:"",backgroundColor:"blue",position:"topRight",message:"&#11198; We're sorry, but you've reached the end of search results.",messageColor:"white"}))}catch(e){console.error(e.message)}finally{f()}}function p(e){return`
    <div class="photo-card">
      <a class="link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
        <li><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
        <li><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
        <li><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
        <li><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
      </div>
      </a>
    </div>
  `}function m(){const e=document.querySelector(".loader");e.style.display="block"}function f(){const e=document.querySelector(".loader");e.style.display="none"}function C(){const e=document.querySelector(".gallery");e.innerHTML=""}const S=document.querySelector(".form"),h=document.querySelector(".input"),q=document.querySelector(".js-load-more");q.style.display="none";S.addEventListener("submit",async e=>{e.preventDefault(),C();const t=h.value.trim();if(t.length===0){w();return}m(),h.value="";try{const s=await y(t);L(s)}catch(s){console.log(s.message)}finally{f()}});
//# sourceMappingURL=commonHelpers.js.map
