import{i as f,a as b,S as w}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();document.querySelector(".js-load-more");function S(){f.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"Oh, shit! Type something",messageColor:"white"})}let c="";async function p(e,o=1){c=e;const s="https://pixabay.com/api/",l=new URLSearchParams({key:"44041025-2e091a4b621ea033778029d2c",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15});try{const{data:t}=await b(`${s}?${l}`);if(t.totalHits===0)f.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"&#11198; Sorry, there are no images matching your search query. Please, try again!",messageColor:"white"});else return t.hits}catch(t){console.error(t.message)}}let n;const y=document.querySelector(".gallery"),a=document.querySelector(".js-load-more");function v(e){y.innerHTML=e.map(o=>m(o)).join(""),n?n.refresh():n=new w(".gallery a",{captionDelay:250,captionsData:"alt"}),e.length>0&&e.length<14?a.style.display="none":a.style.display="block"}function q(e){y.insertAdjacentHTML("beforeend",e.map(o=>m(o)).join("")),n&&n.refresh()}a.addEventListener("click",C);let d=1;async function C(){if(c){d+=1,g();try{const e=await p(c,d);if(!e||e.length===0){u(),f.error({icon:"",backgroundColor:"blue",position:"topRight",message:"&#11198; We're sorry, but you've reached the end of search results.",messageColor:"white"}),a.style.display="none";return}q(e);const s=y.lastElementChild.getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"})}catch(e){console.error(e.message)}finally{u()}}}function m(e){return`
    <div class="photo-card">
      <a class="link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
        <li><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
        <li><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
        <li><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
        <li><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
      </div>
      </a>
    </div>
  `}function g(){const e=document.querySelector(".loader");e.style.display="block"}function u(){const e=document.querySelector(".loader");e.style.display="none"}function $(){d=1;const e=document.querySelector(".gallery");e.innerHTML=""}const x=document.querySelector(".form"),h=document.querySelector(".input"),L=document.querySelector(".js-load-more");L.style.display="none";x.addEventListener("submit",async e=>{e.preventDefault(),$();const o=h.value.trim();if(o.length===0){S(),L.style.display="none";return}g(),h.value="";try{const s=await p(o);v(s)}catch(s){console.log(s.message)}finally{u()}});
//# sourceMappingURL=commonHelpers.js.map
