import{i,a as w,S as L}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const v=document.querySelector(".js-load-more");function S(){i.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"Oh, shit! Type something",messageColor:"white"})}let u="";async function p(e,o=1){u=e;const s="https://pixabay.com/api/",n=new URLSearchParams({key:"44041025-2e091a4b621ea033778029d2c",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15});try{const{data:t}=await w(`${s}?${n}`);if(t.hits.length===0)i.error({icon:"",backgroundColor:"#ef4040",position:"topRight",message:"&#11198; Sorry, there are no images matching your search query. Please, try again!",messageColor:"white"}),v.style.display="none";else return t.hits}catch(t){console.error(t.message)}}let a;const f=document.querySelector(".gallery"),c=document.querySelector(".js-load-more");function C(e){f.innerHTML=e.map(o=>m(o)).join(""),a?a.refresh():a=new L(".gallery a",{captionDelay:250,captionsData:"alt"}),c.style.display="block"}function q(e){f.insertAdjacentHTML("beforeend",e.map(o=>m(o)).join("")),a&&a.refresh()}c.addEventListener("click",$);let l=1;async function $(){if(u){l+=1,g();try{const e=await p(u,l);if(!e||e.length===0){y(),i.error({icon:"",backgroundColor:"blue",position:"topRight",message:"&#11198; We're sorry, but you've reached the end of search results.",messageColor:"white"}),c.style.display="none";return}q(e);const s=f.lastElementChild.getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"});const n=e.totalHits,t=Math.ceil(n/15);l>=t&&(c.style.display="none",i.error({icon:"",backgroundColor:"blue",position:"topRight",message:"&#11198; We're sorry, but you've reached the end of search results.",messageColor:"white"}))}catch(e){console.error(e.message)}finally{y()}}}function m(e){return`
    <div class="photo-card">
      <a class="link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
        <li><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
        <li><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
        <li><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
        <li><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
      </div>
      </a>
    </div>
  `}function g(){const e=document.querySelector(".loader");e.style.display="block"}function y(){const e=document.querySelector(".loader");e.style.display="none"}function M(){l=1;const e=document.querySelector(".gallery");e.innerHTML=""}const R=document.querySelector(".form"),h=document.querySelector(".input"),b=document.querySelector(".js-load-more");b.style.display="none";R.addEventListener("submit",async e=>{e.preventDefault(),M();const o=h.value.trim();if(o.length===0){S(),b.style.display="none";return}g(),h.value="";try{const s=await p(o);C(s)}catch(s){console.log(s.message)}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
